### PR TITLE
Revert interface scaling changes when dynamic scaling is set to 1

### PR DESCRIPTION
**Pull request by mitrokosta**
#213 broke interfaces for 1280x1024 resoultion

### CODE REVIEW

**Comment by espkk** [comment]
Could you explain the idea? How the interfaces will be scaled without that code?

**Comment by mitrokosta** [comment]
> Could you explain the idea? How the interfaces will be scaled without that code?

I honestly have no idea, but it worked before with all this code commented out. Hammie needs only this if.

**Comment by Hammie** [comment]
I checked the game scripts and I don't see `bDynamicScaling` being used anywhere. Don't even see it in TEHO, so also not sure how it could be causing problems.

**Comment by ugeen4** [comment]
seems ok for TEHO

**Review by ugeen4 — APPROVED** [review]

**Review by np-c0mp1ete — APPROVED** [review]
It seems it's fine for everybody to merge it, thanks for the PR!

**Pull request merged**
