### PR TITLE
Replace GetKeyState and GetAsyncKeyState with core functions

### PR DESCRIPTION
**Pull request by q4a**
This is few cherry-picks from my linux branch with replaced GetKeyState and GetAsyncKeyState with core functions.

### CODE REVIEW

**Comment by espkk** [comment]
hey @q4a , could you clarify the status of this PR?

**Comment by q4a** [comment]
@espkk Changes in this PR is wrong. Here is few messages about it from discord:
```
mitrokosta — 18.01.2022:
I agree with changing GetKeyState to core functions, but GetKeyState should not be replaced with GetDebugKeyState
The difference is in Debug part
And it is significant

q4a — 18.01.2022:
Ok, I did not know that. Should I create new function in core?

mitrokosta — 18.01.2022:
No, just wait a bit, I’ll explain
GetAsyncKeyState should be replaced with
core.Controls->IsKeyPressed
because core.Controls->GetDebugAsyncKeyState works only if ondebugkeys is enabled in engine.ini
otherwise it returns 0
and keep in mind IsKeyPressed returns bool, not -1/0
Actually you can create GetAsyncKeyState/GetKeyState so you have to do less manually
this GetAsyncKeyState should use IsKeyPressed internally
you should look at PCS_CONTROLS::GetDebugAsyncKeyState to know more

q4a — 18.01.2022:
Yes, I understand my problem - I always looked on virtual functions:
    virtual short GetDebugAsyncKeyState(int vk)
    {
        return GetAsyncKeyState(vk);
    }

    virtual short GetDebugKeyState(int vk)
    {
        return GetKeyState(vk);
    }
PCS_CONTROLS::GetDebugAsyncKeyState is used in real code

q4a — 18.01.2022:
There is few calls like if (LOWORD(GetKeyState(VK_NUMLOCK)) != 0) like in https://github.com/storm-devs/storm-engine/blob/develop/src/libs/location/src/location_camera.cpp#L565
It's not pressed, but toggled. So I need to think..
If the low-order bit is 1, the key is toggled. - https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate

mitrokosta — 18.01.2022:
Hm, we might need an adjustment in IsKeyPressed
We need to find out how numlock state is handled in SDL
we can probably try something like this (SDL_GetModState() & KMOD_NUM) != 0
but encapsulated
```

So problem is more complex and this changes is wrong. I will make better version, but later. I'm focused with render/graphics part now. If you don't like unmerged draft - then close this one, I'll create better one and make another PR.

**Comment by espkk** [comment]
@q4a
I remember the issue, also I don't see any problem with having an unmerged draft until it's fully abandoned :)
I just wanted to clarify your steps regarding this PR. So, thanks for the explanation 👍 
It's up to you to proceed inside this or in a new one. Just let me know if you need any help with this or if you don't plan to finish it.

**Comment by q4a** [comment]
@espkk @mitrokosta - I reworked the changes. Check it, please.

**Comment by q4a** [comment]
I fixed VK_NUMLOCK checking and free_camera now works:
free_camera-fix

**Review by mitrokosta — APPROVED** [review]

**Review by espkk — APPROVED** [review]
cannot test this rn but looks good, thanks!

**Pull request merged**
