### PR TITLE
Change Icons Order

### PR DESCRIPTION
**Pull request by LipsarJ**
Hello. Check screenshot: https://drive.google.com/file/d/1zTFoV4_IqR2LKvASSV0x0Mi_ymL3tNbj/view?usp=sharing

### CODE REVIEW

**Comment by ugeen4** [comment]
Please show screenshot before and after changes

**Comment by LipsarJ** [comment]
> Please show screenshot before and after changes

https://drive.google.com/file/d/1dLFXNsltew0Cdt9WA-E_-2WL1itElzkc/view?usp=sharing Before Changes
https://drive.google.com/file/d/1zTFoV4_IqR2LKvASSV0x0Mi_ymL3tNbj/view?usp=sharing After Changes

**Review by ugeen4 — DISMISSED** [review]
looking good!

**Review by espkk — COMMENTED** [review]
looks good, but I'd rather make this configurable. it shouldn't be difficult to do if we introduce a dedicated event for order configuration

**Comment by LipsarJ** [comment]
> looks good, but I'd rather make this configurable. it shouldn't be difficult to do if we introduce a dedicated event for order configuration

I will surprised if someone want to change order into other :)

**Review by mitrokosta — CHANGES_REQUESTED** [review]
I object to such changes unless they are configurable. The old order was fine by me and I don't want to be forced to use another.
P.S. Default order should be the current one, so those who don't want this change won't have to hastily make adjustments in their existing code base.

**Comment by LipsarJ** [comment]
I've added configuration by attribute in battleinterface

**Review by mitrokosta — DISMISSED** [review]

**Comment by espkk** [comment]
Modified to be fully configurable via script event. Event snippet:
```#event_handler(BI_EVENT_GET_CMD_LIST_ORDER_PRIORITY, "BI_GetCmdListOrderPriority");
ref BI_GetCmdListOrderPriority()
{
  int curItem = GetEventData();

  if(curItem < 0 || curItem > 13) {
    return;
  }

  int i = 0;
  int cmdList[14];
  cmdList[i] = BI_COMMODE_NOTDISEASED_TOWN; i++;
  cmdList[i] = BI_COMMODE_DISEASED_TOWN; i++;
  cmdList[i] = BI_COMMODE_ENEMY_TOWN; i++;
  cmdList[i] = BI_COMMODE_LAND_SELECT; i++;
  cmdList[i] = BI_COMMODE_FRIEND_FORT_SELECT; i++;
  cmdList[i] = BI_COMMODE_NEUTRAL_FORT_SELECT; i++;
  cmdList[i] = BI_COMMODE_ENEMY_FORT_SELECT; i++;
  cmdList[i] = BI_COMMODE_MY_SHIP_SELECT; i++;
  cmdList[i] = BI_COMMODE_NEUTRAL_SHIP_SELECT; i++;
  cmdList[i] = BI_COMMODE_FRIEND_SHIP_SELECT; i++;
  cmdList[i] = BI_COMMODE_ENEMY_SHIP_SELECT; i++;
  cmdList[i] = BI_COMMODE_COMMAND_SELECT; i++;
  cmdList[i] = BI_COMMODE_CANNON_CHARGE; i++;
  cmdList[i] = BI_COMMODE_USER_ICONS; i++;

  BI_intRetValue = cmdList[curItem];
  return &BI_intRetValue;
}
```

**Pull request merged**
