### PR TITLE
[CI] Update Windows CI

### PR DESCRIPTION
**Pull request by espkk**

### CODE REVIEW

**Review by Hammie — DISMISSED** [review]

**Comment by espkk** [comment]
should be fine now

**Comment by q4a** [comment]
@espkk can you remove `"jobs": 8` ? I think that all has different HW and CI has less then 8 cores.

**Comment by espkk** [comment]
> @espkk can you remove `"jobs": 8` ? I think that all has different HW and CI has less then 8 cores.

CI should override thread count with the actual number of cores

**Comment by q4a** [comment]
Ok. What about people that have 4-6 or 24 cores?
I tested on my old Windows PC with 4 cores and this looks wrong:
image

**Comment by espkk** [comment]
> Ok. What about people that have 4-6 or 24 cores? I tested on my old Windows PC with 4 cores and this looks wrong: image

It should be possible to override with the `-j` flag. 8 is an informal default for `-j`

The problem is that we already have msvc parallel build enabled, so it should be already optimal. While parallel project building increases contention

I'm not sure yet if we can disable it for windows builds only without introducing a new build preset, but since so far it's only used for windows builds, we can just disable it completely

**Comment by q4a** [comment]
UPD: I removed `"jobs": 8` and got better results:
image
It's still 4-6 threads, but it's not 8 at least.

**Comment by espkk** [comment]
@q4a, check my previous answer. in worst case it might be cores x 8 on windows

PS don't merge this yet, let me squash

**Pull request merged**
