### PR TITLE
Replace conanfile.txt with conanfile.py; replace generator to support multi

### PR DESCRIPTION
**Pull request by espkk**
This basically aimed to support multi-config environments like Visual Studio.
Empowered with conanfile.py this PR also completely removes Steamworks dependency when building without steam and moves resource folder deploy into conanfile.py. Some dependencies were also updated/derived from the official artifactory.

What I expect to be broken atm:
CI (needs to adjust paths)
PROBABLY environments that don't use multi-config (e.g. ninja without multi-config enabled)

Could someone check the latter?

### CODE REVIEW

**Comment by ugeen4** [comment]
just check this PR : checkout & remove .conan from home dir, remake cache (and update conan), compile (w/o steam), run TEHO. Don't see problems at all

**Review by np-c0mp1ete — COMMENTED** [review]
Please check if everything still works when opening and building the project using the Visual Studio support for CMake.

**Comment by espkk** [comment]
should be good now:
- build without sln is ok
- CI is ok
- correct fmod variant is used

**Review by Hammie — APPROVED** [review]
Also works for me!

**Pull request merged**
