### PR TITLE
Fix crash when no lines need to be drawn in the battle navigator

### PR DESCRIPTION
**Pull request by Hammie**
Just a quick fix for a crash I encountered while debugging New Horizons

### CODE REVIEW

**Comment by q4a** [comment]
Looks good. Thanks!

**Review by espkk — COMMENTED** [review]
Hey. I'm wondering how this caused a crash for you. `DrawLines2D` returns immediately if the second parameter==0
Therefore, I don't see any difference between `empty()` and `size() / 2`
But maybe I'm missing something...

**Comment by Hammie** [comment]
@espkk It's a debug assertion triggered by doing `&lines[0]`, so probably only crashes in debug builds.

**Comment by espkk** [comment]
> @espkk It's a debug assertion triggered by doing `&lines[0]`, so probably only crashes in debug builds.

Ah...you're right, it makes sense
Though we don't dereference memory the access operator cannot know that
It's very likely that operator[] is not allowed to be used on an empty array

However, we can safely put `std::data(lines)` instead, right? Or even pass a cref to a vector, but then we'll likely have to rewrite some other portions of code

I mean I also don't mind `empty()` check. But to me it just sounds consistent enough that we pass a buffer with zero objects to draw and it works fine

**Comment by Hammie** [comment]
@espkk `data()` does work so I updated the code

**Review by espkk — APPROVED** [review]

**Pull request merged**
